@startuml

header TerminalProxy

title CorrectionReceipt
caption (item: TicketItem, need_device: bool)

start

:retCode = -1
fItem = null
rsp = Cmd.CorReceiptStart();
if (rsp.result?) then (err)
	:return ResultItem(
		Code = rsp.err_core,
		Result = fItem);
	stop
endif
:hexData = List(str)
TLVPostion = 0
TLV += (1021, item.company_authorized_person_name)
TLV += (1203, item.CompanyInn)
hexData = TLV.Take(TLVPosition).hex()
localDate = now() + 3h ' MSK+3? UTC+3?'
TLV += CorrectionBase(item.DateTrip)
hexData = TLV.Take(TLVPosition).hex()
TLV += (1055, item.Tax)
hexData = TLV.Take(TLVPosition).hex()
TLV += (1031, item.PaymentType == 1 ? item.Price : 0)
hexData = TLV.Take(TLVPosition).hex()
TLV += (1081, item.PaymentType == 2 ? item.Price : 0)
TLV += (1215, 0)
TLV += (1216, 0)
TLV += (1217, 0)
hexData = TLV.Take(TLVPosition).hex()
TLV += (1102, (item.Vat == "NDS20" ? item.Price : 0))
TLV += (1103, (item.Vat == "NDS10" ? item.Price : 0))
TLV += (1104, (item.Vat == "NDS0" ? item.Price : 0))
TLV += (1105, (item.Vat == "NONDS" ? item.Price : 0))
TLV += (1106, (item.Vat == "NDS20_120" ? item.Price : 0))
TLV += (1007, (item.Vat == "NDS10_110" ? item.Price : 0));
:rsp = Cmd.CorReceiptData, TLV.Take(TLVPosition));
if (rsp.result?) then (err)
	:return ResultItem(
		Code = rsp.err_core,
		Result = fItem);
	stop
endif
if (need_device) then (ok)
	:TLVPosition = 0
	TLV += (1009, item.CompanyAddress)
	TLV += (1187, item.company_paymentPlace)
	TLV += (1036, "1");
	:rsp = Cmd.CorReceiptSendAutoDevice(TLV.Take(TLVPosition));
endif
:data = prepared item.Price;
:rsp = Cmd.MakeCorReceipt(data, item.id);
if (rsp.result) then (err)
	:Cmd.CancelDocument();
	:return ResultItem(
		Code = retCode,
		Result = fItem);
	stop
endif
:fItem = ParseCorReceiptResponse(rsp)
fItem.ReceiptType = 8
doc = GetDocument(fItem.FiscalNum)
fItem.ReceiptDate = doc.documentdate
retCode = 0;
if (fItem?) then (!null)
	:fItem.TicketId = item.Id
	fItem.FiscalStatus = 7
	fItem.Ms = <time cutoff>;
endif
:return ResultItem(Code = retCode, Result = fItem);

stop

@enduml
